package otus.gpb.recyclerview

data class GroupChat (
    override var id: Int,
    val groupName: String,
    val lastAuthor: String,
    val lastMessage: String,
    val avatarUrl: String,
    val messagePreviewUrl: String,
    var voip: Boolean,
    var verified: Boolean,
    var muted: Boolean,
    val time: String,
    var checked: Boolean,
    var read: Boolean,
    var mentioned: Boolean,
    var pinned: Boolean,
    var counter: Int
) : ChatItem

val groupChatList = listOf(
    GroupChat(
        id = 1,
        groupName = "Новости Уренгоя",
        lastAuthor = "Рустам",
        lastMessage = "Ямы в асфальте",
        avatarUrl = "https://upload.wikimedia.org/wikipedia/commons/0/07/Coat_of_Arms_of_Novy_Urengoy_%28Yamal_Nenetsia%29.png",
        messagePreviewUrl = "https://s.ura.news/1200_900/images/news/upload/news/563/455/1052563455/61347_Yama_v_asfalyte_Chelyabinsk_yama_na_asfalyte_250x0_3920.2208.0.0.jpg",
        voip = true,
        verified = false,
        muted = true,
        time = "12:01",
        checked = false,
        read = false,
        mentioned = true,
        pinned = true,
        counter = 0
    ),
    GroupChat(
        id = 2,
        groupName = "Наука и техника",
        lastAuthor = "Наука 2.0",
        lastMessage = "Сегоня русскими учёными был открыт..",
        avatarUrl = "https://img.freepik.com/free-vector/cheerful-professor-giving-lecture_1308-166876.jpg",
        messagePreviewUrl = "",
        voip = true,
        verified = false,
        muted = true,
        time = "23:08",
        checked = false,
        read = true,
        mentioned = true,
        pinned = false,
        counter = 0
    ),
    GroupChat(
        id = 3,
        groupName = "Космос",
        lastAuthor = "admin",
        lastMessage = "Космическое пространство, космос...",
        avatarUrl = "https://abrakadabra.fun/uploads/posts/2022-02/1644750437_4-abrakadabra-fun-p-kosmicheskie-avatarki-10.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = false,
        muted = true,
        time = "16:22",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 0
    ),
    GroupChat(
        id = 4,
        groupName = "Растения России",
        lastAuthor = "админ",
        lastMessage = "В Россия вы можете найти Тысячелистник...",
        avatarUrl = "https://www.picturethisai.com/image-handle/website_cmsname/image/1080/201229495676567552.jpeg?x-oss-process=image/format,webp",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "14:56",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 50
    ),
    GroupChat(
        id = 5,
        groupName = "Быстрее всех",
        lastAuthor = "Руслан",
        lastMessage = "Кто хочет стать миллионером?",
        avatarUrl = "https://info.sibnet.ru/ni/285/285233b.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "16:08",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 312
    ),
    GroupChat(
        id = 6,
        groupName = "Собаки и кошки",
        lastAuthor = "Женя",
        lastMessage = "Коротко о братьях меньших..",
        avatarUrl = "https://www.kadrof.ru/sites/default/files/illustrations/cat_dogs_0_0.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "Вт",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 1
    ),
    GroupChat(
        id = 7,
        groupName = "Гоночные машины",
        lastAuthor = "Олег",
        lastMessage = "машина как пушка!",
        avatarUrl = "https://avtorinok.ru/storage/news/pics/2011/19684.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "14:56",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 5
    ),
    GroupChat(
        id = 8,
        groupName = "Памяти предков",
        lastAuthor = "Аркадий",
        lastMessage = "Тогда, под Сталниградом..",
        avatarUrl = "https://stihi.ru/pics/2016/05/20/6502.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "14:56",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 14
    ),
    GroupChat(
        id = 9,
        groupName = "Звезда",
        lastAuthor = "Генерал",
        lastMessage = "Тонкая грань между..",
        avatarUrl = "https://avatarko.ru/img/avatar/2/prazdnik_zvezda_1360.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "00:14",
        checked = true,
        read = true,
        mentioned = false,
        pinned = false,
        counter = 4
    ),
    GroupChat(
        id = 10,
        groupName = "Мисс Египет",
        lastAuthor = "Ра",
        lastMessage = "...она была недовольна!",
        avatarUrl = "https://i.pinimg.com/236x/95/be/a6/95bea63153271f1ea054eacf99ba85c2.jpg",
        messagePreviewUrl = "",
        voip = false,
        verified = true,
        muted = false,
        time = "Чт",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 2
    )
)