package otus.gpb.recyclerview

data class PersonChat(
    override var id: Int,
    val personName: String,
    val lastMessage: String,
    val avatarUrl: String,
    val messagePreviewUrl: String = "",
    var checkbox: Boolean,
    var online: Boolean,
    var locked: Boolean,
    var scam: Boolean,
    var verified: Boolean,
    var muted: Boolean,
    val time: String,
    var checked: Boolean,
    var read: Boolean,
    var mentioned: Boolean,
    var pinned: Boolean,
    var counter: Int
) : ChatItem

val personChatList = listOf(
    PersonChat(
        id = 1,
        personName = "Дима Булыгин",
        lastMessage = "Как дела?",
        avatarUrl = "https://99px.ru/cms/temp/module_temp1/image1_image_111102521392452924164x64.jpg",
        checkbox = false,
        online = true,
        locked = false,
        scam = false,
        verified = true,
        muted = false,
        time = "Ср",
        checked = true,
        read = false,
        mentioned = false,
        pinned = true,
        counter = 0
    ),
    PersonChat(
        id = 2,
        personName = "Оксана Политковская",
        lastMessage = "Ничего не бойся, я с тобой",
        avatarUrl = "https://shapka-youtube.ru/wp-content/uploads/2021/03/kartinka-na-avatarku-dlya-devushek.jpg",
        checkbox = false,
        online = true,
        locked = false,
        scam = false,
        verified = true,
        muted = false,
        time = "Ср",
        checked = true,
        read = false,
        mentioned = false,
        pinned = true,
        counter = 0
    ),
    PersonChat(
        id = 3,
        personName = "Олег Кошевой",
        lastMessage = "Будь моложе",
        avatarUrl = "https://99px.ru/sstorage/1/2025/08/image_11508251524124353275.jpg",
        checkbox = false,
        online = false,
        locked = false,
        scam = false,
        verified = false,
        muted = false,
        time = "Вт",
        checked = true,
        read = false,
        mentioned = false,
        pinned = true,
        counter = 0
    ),
    PersonChat(
        id = 4,
        personName = "Павлик Дуров",
        lastMessage = "Блин, я в тюрьме, в Париже..",
        avatarUrl = "https://images.techinsider.ru/upload/img_cache/c61/c61b042b8f2cb917787a0968a8753d52_cropped_510x340.webp",
        checkbox = false,
        online = true,
        locked = true,
        scam = true,
        verified = false,
        muted = true,
        time = "06:43",
        checked = false,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 999
    ),
    PersonChat(
        id = 5,
        personName = "Баста",
        lastMessage = "Йо, братан, как дела?",
        avatarUrl = "https://cdn.kassir.ru/krd/poster/8e/8e58de873fcd911b8ac6c2ea20f17062.jpg",
        checkbox = false,
        online = false,
        locked = false,
        scam = false,
        verified = true,
        muted = false,
        time = "15:01",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 0
    ),
    PersonChat(
        id = 6,
        personName = "CatBird",
        lastMessage = "Что ты будешь делать?",
        avatarUrl = "https://img.freepik.com/premium-vector/vector-hand-drawn-doodle-sketch-catbird-bird_982534-5454.jpg",
        checkbox = false,
        online = false,
        locked = false,
        scam = false,
        verified = true,
        muted = false,
        time = "Вс",
        checked = false,
        read = false,
        mentioned = false,
        pinned = true,
        counter = 0
    ),
    PersonChat(
        id = 7,
        personName = "Moonlight",
        lastMessage = "Сегодня ночью дождь",
        avatarUrl = "https://img.freepik.com/premium-vector/white-moon-cartoon-with-star-sky_43633-3705.jpg",
        checkbox = false,
        online = true,
        locked = false,
        scam = false,
        verified = true,
        muted = false,
        time = "Ср",
        checked = true,
        read = false,
        mentioned = false,
        pinned = true,
        counter = 0
    ),
    PersonChat(
        id = 8,
        personName = "trololo",
        lastMessage = "Ахахаха",
        avatarUrl = "https://i.pinimg.com/736x/da/a8/5b/daa85b83a914eeaef3151dd019f207bf.jpg",
        checkbox = false,
        online = false,
        locked = false,
        scam = false,
        verified = false,
        muted = false,
        time = "Вт",
        checked = true,
        read = false,
        mentioned = false,
        pinned = true,
        counter = 0
    ),
    PersonChat(
        id = 9,
        personName = "Oleg",
        lastMessage = "Кто тут?",
        avatarUrl = "https://cdn.dprofile.ru/public/29275/profile/fd8a6309071b165f6fb1d30b3747cf4eb6137177.jpg",
        checkbox = false,
        online = false,
        locked = true,
        scam = true,
        verified = false,
        muted = false,
        time = "06:43",
        checked = false,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 0
    ),
    PersonChat(
        id = 10,
        personName = "Котёнок",
        lastMessage = "Новые машины завезли...",
        avatarUrl = "https://w7.pngwing.com/pngs/873/489/png-transparent-avatar-youtube-cat-cute-dog-heroes-cat-like-mammal-carnivoran.png",
        checkbox = false,
        online = false,
        locked = false,
        scam = false,
        verified = true,
        muted = false,
        time = "15:01",
        checked = true,
        read = false,
        mentioned = false,
        pinned = false,
        counter = 0
    )
)